version: '3'

services:
  flask:
    container_name: linebot-python
    build: ./app
    ports:
      - 5000:5000
    links:
      - mysql
    privileged: true
    volumes:
      - ./app:/app
    tty: true
    environment:
        TZ: Asia/Tokyo
        FLASK_ENV: 'development'
        FLASK_APP: 'app.py'
    command: flask run -h 0.0.0.0

  mysql:
    container_name: linebot-db
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
